server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather-forecast-database
    username: weather-forecast-admin
    password: dummypassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
